
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/mecenas}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
  thymeleaf:
    cache: false
flyway:
  enabled: true
  locations: classpath:db/migration
server:
  port: ${PORT:8080}
app:
  baseUrl: ${APP_BASE_URL:http://localhost:8080}
stripe:
  secretKey: ${STRIPE_SECRET_KEY:sk_test_xxx}
  webhookSecret: ${STRIPE_WEBHOOK_SECRET:whsec_xxx}
  price:
    weekly: ${STRIPE_PRICE_WEEKLY:price_xxx}
    monthly: ${STRIPE_PRICE_MONTHLY:price_xxx}
    annual: ${STRIPE_PRICE_ANNUAL:price_xxx}
aws:
  s3:
    bucket: ${S3_BUCKET:mecenas-demos}
    region: ${S3_REGION:sa-east-1}
    accessKey: ${S3_ACCESS_KEY_ID:}
    secretKey: ${S3_SECRET_ACCESS_KEY:}
